### ISSUE TITLE
Split "missing tags" check in three categories

### ISSUE THREAD

**Issue by poppei82** [keepright/keepright#10]
Hi!

For more fluent correcting of "missing tags" I suggest to split this into three categories:
- way has no tags
- node has no tags
- node/way has no value

Currently everything is mixed in one check. So that if you correct things, you have to switch mentally, what to do. Sure, there is a text in the info-bubble. But normally you don't read that before you correct the error. Especially when using QAT-Script, you don't read the info but correct the error quickly.

When this check is split into these categories, you know that you ONLY see nodes or ONLY have to check the value. Maybe this would enhance the speed of correcting.

Thanks!

**Comment by mueschel** [comment]
Reading through the old issues I noticed I did just this last weekend, albeit for other reasons.
