### ISSUE TITLE
exclude highway=platform from almost-junctions-check

### ISSUE THREAD

**Issue by poppei82** [keepright/keepright#16]
Hi!

For pedestrian navigation it is useful to link highway=platform to the normal streets by using highway=footway. It is not necessary to link every end-node to the streets but it can be done by just linking it with one highway=footway to the middle of the platform.

highway=platform is legacy, however used very often. Also it is used as a single way, not as an area=yes.

Nevertheless keepright finds an error when highway=platform is close to a street by its end-node, though it is linked to the street by a highway=footway

You see that around Kaiserslautern/Germany (not only there!). See "ignored errors": http://keepright.at/report_map.php?lang=en&ch191=1&ch195=1&ch196=1&number_of_tristate_checkboxes=8&highlight_error_id=0&highlight_schema=0&lat=49.44532&lon=7.77282&zoom=19&show_ign=1&show_tmpign=0&layers=B0T&ch=0%2C50

Perhaps this is a nice check for "floating islands"?

Thanks!

**Comment by mueschel** [comment]
Already done, forgot to close this issue.
