### ISSUE TITLE
check for other "suspicious values" (unknown tags)

### ISSUE THREAD

**Issue by poppei82** [keepright/keepright#23]
Hi!

In the past I often corrected "missing tags". In some regions there were plenty of lines which were destroyed by OSMF Redaction Bot. So the missing tags check was a nice tool to find those errors.

However the OSMF Redaction Bot did not simply deleted nodes and tags. It deleted only nodes and tags, which were inserted by users who did not agree to the new license. This leads to many ways which were nonsense: there was only a "tracktype=grade3". Such a way will not be rendered. And also it is difficult to find, because they are shown as grey lines in JOSM.

Also I accidently found this way which was made by a newbie: http://www.openstreetmap.org/way/261259678

So maybe - as an addition to new "suspicious values" check or to "deprecated tags" check - it is possible to implement a check for values which are nonsense or where possibly other values are missing. Would make it easier to find not only missing data, but nonsense data which isn't properly tagged.

Just an idea.

Thanks!

**Comment by mueschel** [comment]
* tracktype without highway is included now
* name without any other tag is included now
* source & created_by tags are already excluded when checking for keys without tags
* buildings with ref is actually used, so no simple check possible
* lanes without highway is included, but might lead to unwanted false positives 
* the rest might be obvious for the human eye, but I can't think of any automatic scheme to find these problems.

**Comment by mueschel** [comment]
You can find the errors reported by these new checks here:
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=14&lat=50.25&lon=8.75&layers=B0T&ch=0%2C73%2C75
