### ISSUE TITLE
warn about waterways with layer=-1 which are not in a tunnel, culvert or similar

### ISSUE THREAD

**Issue by RicoZ-OSM** [keepright/keepright#24]
Many mappers tag whole rivers or long sections of those with layer=-1 with the intention to hide warnings about missing bridges etc. This defeats virtually all error checks of JOSM and keepright.

The useful combinations of (waterway=* AND layer=-1) are (tunnel=* OR culvert=yes  OR covered=*  OR pipeline=yes  OR location=underground)

Everything else should give a warning.

**Comment by mueschel** [comment]
This check is now implemented. First results are visible around Frankfurt:
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=10&lat=50.20981&lon=8.64144&ch=0%2C233
