### ISSUE TITLE
Exclude highway=construction, highway=proposed, railway=construction, railway=razed, and railway=proposed from some checks

### ISSUE THREAD

**Issue by sb12** [keepright/keepright#26]
I think these values should be excluded from checks like "missing railway crossing", "dead-ended oneways", "almost junctions", "intersections without junctions" and "floating islands". In most cases these highways and railways are not connected on purpose, e.g. because it's not known yet how they will be connected or how they will continue. With railway crossings this even promotes to map features which are not there yet/anymore.
Example area with lot's of these errors: http://keepright.ipax.at/report_map.php?zoom=19&lat=49.00906&lon=8.41806

**Comment by mueschel** [comment]
Seems like these cases are handled well now.
