### ISSUE TITLE
exclude/optimize building:colour-guesses in misspelled tags-check

### ISSUE THREAD

**Issue by poppei82** [keepright/keepright#33]
Hi!

I found a lot of errors in Weseling near Cologne: http://keepright.at/report_map.php?zoom=14&lat=48.20808&lon=16.37221

The guesses of building:colour are wrong (I think).

Thanks!

**Comment by mueschel** [comment]
Forgot to close this issue. building:colour and roof:colour are removed from the misspelled tags check
