### ISSUE TITLE
Enhance check about highways crossing waterways without bridge/tunnel

### ISSUE THREAD

**Issue by RicoZ-OSM** [keepright/keepright#34]
Currently, many users mark whole rivers with layer=-1 because this will silence keepright warnings about missing bridges/tunnels.

Enhance the check so that keepright warns whenever a highway crosses a waterway where there is no bridge or tunnel even if layer is different. A layer tag itself does not make a valid bridge or tunnel.

This has been discussed  in the wiki ( https://wiki.openstreetmap.org/wiki/Talk:Key:layer#layer.3D-1_erroneously_used_for_many_italian_rivers ) and previously the update to https://wiki.openstreetmap.org/wiki/Key:layer has been discussed in the mailing list ( https://lists.openstreetmap.org/pipermail/talk/2014-March/069219.html )

Related to issues #24 and #25

**Comment by mueschel** [comment]
This can be closed, there are other issues addressing the same points.
