### ISSUE TITLE
find addr:housename with numeric values

### ISSUE THREAD

**Issue by werner2101** [keepright/keepright#37]
addr:housename and addr:housenumber are very similar tags. As housename is listet before housenumber in the editors, housename might often be used accidently instead of housenumber.

Keepright could created a warning for numeric addr:housename values.

see also (from tagging mailing list):
[1] http://taginfo.openstreetmap.org/keys/addr%3Ahousename#values
[2] http://wiki.openstreetmap.org/wiki/Key:addr
[3] https://github.com/openstreetmap/iD/issues/1525
[4] https://github.com/openstreetmap/iD/issues/2124

Regards
Werner

**Comment by mueschel** [comment]
Added it. Let's see how it works. Are there any other tags where a numeric value is suspicious?

**Comment by werner2101** [comment]
No, that's the only one I stumbled over.

**Comment by mueschel** [comment]
Forgot to mention, you can see the result here:
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=9&lat=50.05628&lon=8.71153&layers=B0T&ch=0%2C423&show_ign=1&show_tmpign=1
