### ISSUE TITLE
Flag tiger:reviewed as a warning

### ISSUE THREAD

**Issue by bhousel** [keepright/keepright#39]
As of 2014 I think there are enough people editing the map that I basically see `tiger:reviewed` the same as `fixme`.  It's unusual for roads to still have this tag in heavily edited areas.

**Comment by mueschel** [comment]
Almost two years later there is no change, still 12 million. These are too many to be included in the database (currently only 32 million errors / warnings world-wide). Actually, I think that people just don't remove this tag when editing a road and it has no useful meaning any more.
