### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by Klumbumbus** [keepright/keepright#44]
There is a text overflow in the german version and a scroll bar under the popup.

![screenshot](http://images.devs-on.net/Image/jK8ZsStlQMEw585o-Bereich.png)

other example:
![screenshot](http://images.devs-on.net/Image/d2LKaLDuaxYlR6Aj-Bereich.png)

**Comment by mueschel** [comment]
I set a fixed font-size now - before it was up to the browsers defaults.
