### ISSUE TITLE
Integrate with http://maproulette.org/

### ISSUE THREAD

**Issue by brycenesbitt** [keepright/keepright#5]
Map Roulette is kind of a 'one at a time' version of KeepRight, available at http://maproulette.org/

With a suitable export format, KeepRight flags could be fed to Map Roulette.

**Comment by brycenesbitt** [comment]
http://maproulette.org/#t=webtegrity/ is using keepright data now.

**Comment by mueschel** [comment]
Is there anything to be changed on the export part of Keepright? I think the formats available are sufficient.
