### ISSUE TITLE
Add cross-origin HTTP request header

### ISSUE THREAD

**Issue by mvl22** [keepright/keepright#53]
Related to issue #52:

Would you be able to add a cross-origin HTTP request header, so that requests from an external Javascript map can use that GeoJSON?

You just need to add to the PHP:

    header ('Access-Control-Allow-Origin: *');

There are details of this at:
https://developer.mozilla.org/En/HTTP_access_control

**Comment by mueschel** [comment]
I added it.

**Comment by mvl22** [comment]
Brilliant - thanks. I can see that coming through nicely.
