### ISSUE TITLE
Europe bounding box recently was reduced

### ISSUE THREAD

**Issue by matkoniecz** [keepright/keepright#55]
I am editing in Kraków, Poland ( http://www.openstreetmap.org/#map=14/50.0735/19.9205 ).

Unfortunately recently bounding box was reduced and it no longer is reaching this area. Is it possible to revert this? 

See http://keepright.at/report_map.php?zoom=14&lat=48.20808&lon=16.37221 for eastern bounding box limit.

![selection_002](https://cloud.githubusercontent.com/assets/899988/13285235/d3d3f6dc-daf9-11e5-9744-7c60e0edd530.png)

**Comment by mueschel** [comment]
Hi,
checks are run for the whole world, no bounding boxes involved. But the world is divided into regions and it seems the last run for your area has failed. 
I forwarded the information to Harald, the region will likely be available in a few days again.

**Comment by mueschel** [comment]
There was a problem during upload of the errors to the server, now everything is back to normal.
Thanks for reporting!
