### ISSUE TITLE
RSS export feature not working anymore

### ISSUE THREAD

**Issue by sb12** [keepright/keepright#57]
Hi,
since about October 2015 I don't get any updates for new errors via the RSS export function on [http://keepright.ipax.at/](http://keepright.ipax.at/). When I click on the RSS Link in the bottom left corner of the page I just get an [empty feed](http://keepright.ipax.at/export.php?format=rss&ch=0,30,40,50,70,90,100,120,130,150,160,180,191,192,193,194,195,196,197,198,201,202,203,204,205,206,207,208,210,220,231,232,270,281,282,283,284,291,292,293,311,312,313,350,380,411,412&left=16.298601601037788&bottom=48.16212786841002&right=16.48193595162461&top=48.23810115249676).
Could you check whether something is broken here? This feed helped a lot to quickly find errors in my area and fix them.
Thanks for your work.

**Comment by mueschel** [comment]
Hi,
thanks for reporting. It's not always empty, but to me it seems something is wrong there... We're having a look.

**Comment by mueschel** [comment]
This should be solved - RSS is filled again (maybe only with the next update of your area).

**Comment by sb12** [comment]
Thanks for the quick fix. It's working, I got a lot of new errors to fix in my rss feed this morning.
