### ISSUE TITLE
hide (most) waterway crosses highway cases by default, more granularity

### ISSUE THREAD

**Issue by RicoZ-OSM** [keepright/keepright#58]
Small paths/tracks etc crossing small creeks is a missing data situation in probably 90-99% of cases and most of the time you can not correct them even with good Bing coverage. It could be a small bridge, culvert, ford, no way to know without local knowledge.

Unfortunately I have witnessed too many coach mappers trying to correct these in incorrect ways, some of them attach layer=-1 to the whole stream, others may be doing more subtle errors not so easy to detect.

Hence displaying this error for small creeks and small highways does much more harm than good, in addition JOSM already has a test for it anyway.

One possibility would be to turn the test off by default, another would be to test only for rivers and/or major highways.

**Comment by brycenesbitt** [comment]
Agreed!  The keepright test is well meaning, but doing more harm than good.

**Comment by mueschel** [comment]
I agree that it might be a good idea to limit the check on crossings of rivers/streams etc. with major highways. But for lakes and riverbanks I would like to keep the check on all types of ways - if there is a crossing, then it usually is a problem of way geometry and not because there is bridge/ford/culvert tag missing.

**Comment by RicoZ-OSM** [comment]
@mueschel: could work fine that way, lets see in practice.

Also https://github.com/keepright/keepright/issues/24 describes a very easy test to find erroneous layer tags on waterways.

**Comment by RicoZ-OSM** [comment]
Btw it would be nice if _something_ could be done quickly. The exact details can be fine tuned later but the current state has been a nuisance for too long time.

**Comment by bhousel** [comment]
I think we should leave the warnings.  Validation is a task for more experienced mappers.  

If you find new users mistagging waterways just to make warnings go away, you should contact them politely in a changeset comment.  I doubt this is a widespread problem in OSM. 

Related: It's possible I messed something up in 0466110ecdc4b72daa5c282f629285d883721f55 
That commit was supposed to prevent warnings about highway-waterway crossings where the highway is tagged as a 'ford'.  
But I still see a bunch of them on keepright. (e.g. [here](http://keepright.ipax.at/report_map.php?zoom=16&lat=40.6823&lon=-74.38021&layers=B0T&ch=0%2C30%2C40%2C50%2C70%2C90%2C100%2C110%2C120%2C130%2C150%2C160%2C170%2C180%2C191%2C192%2C193%2C194%2C195%2C196%2C197%2C198%2C201%2C202%2C203%2C204%2C205%2C206%2C207%2C208%2C210%2C220%2C231%2C232%2C270%2C281%2C282%2C283%2C284%2C285%2C291%2C292%2C293%2C294%2C295%2C296%2C297%2C298%2C311%2C312%2C313%2C320%2C350%2C370%2C380%2C401%2C402%2C411%2C412%2C413&show_ign=1&show_tmpign=1))

**Comment by mueschel** [comment]
@bhousel  Please check on http://osm.mueschelsoft.de/keepright/  It might be a discrepancy between the official instance (still run by Harald Kleiner) and the code in this repo.

**Comment by bhousel** [comment]
> Please check on http://osm.mueschelsoft.de/keepright/ It might be a discrepancy between the official instance (still run by Harald Kleiner) and the code in this repo.

oh sorry, you are right.. I was looking at the wrong one.

**Comment by RicoZ-OSM** [comment]
I sent probably 200 private messages related to this issue and helped 2 mobile rendering projects to workaround problems caused by wrong layers.

Although admittedly only some fraction of the problem was caused by keepright but I keep stumbling upon wonderful edits like https://www.openstreetmap.org/changeset/19923982 way too often. Two years after I have cleaned up a small area in central Europe I find unbelievable 6987 waterways with 

 `waterway=* layer=-1 -tunnel=* -culvert=yes -covered=yes -pipeline=yes -location=underground nodes:4-`

out of which at least 99% are errors or crude hacks to workaround those pesky keepright warnings. Why don't you implement this check instead?

**Comment by bhousel** [comment]
I don't think it's really fair to blame keepright for flagging a valid map issue.  Besides, isn't it trivial to clean that up with an Overpass query and JOSM?

By the way, I do hope all the people arguing for _more_ validation in iD are paying attention..

**Comment by RicoZ-OSM** [comment]
You could implement the trivial test pointed out above and I promise I will never blame keepright again. It should be one of the easiest checks you have ever implemented?

Your test is correct but nevertheless creates more problems than it solves so at some point it is fair to blame the tool. In addition keepright fails to recognise other more important problems because of this issue.. just fixed two overlapping rivers which keepright did not detect because they had different layers.

It is "easy" to cleanup with an overpass query and JOSM but mechanical edits are strongly discouraged. So although I am fairly pretty sure my filter is 100% correct I have to review every single change.

**Comment by mueschel** [comment]
> waterway=* layer=-1 -tunnel=* -culvert=yes -covered=yes -pipeline=yes -location=underground nodes:4-

This check is now implemented and seems to work well. You can see the first errors around Frankfurt: 
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=10&lat=50.20981&lon=8.64144&ch=0%2C233

**Comment by RicoZ-OSM** [comment]
Thanks. The message for the strange layer of waterway could be tweaked a bit, culvert=yes is outdated, pipeline + location usually should go together.

So perhaps "This waterway has layer=-1 but no tag indicating that it actually is underground. If it is a tunnel, culvert or pipeline consider adding the appropriate tags describing this, otherwise consider removing the unneeded layer tag"

**Comment by mueschel** [comment]
Changed.
