### ISSUE TITLE
0270_motorways_connected_directly - extend query with vehicle=no; verify parking_aisle, services

### ISSUE THREAD

**Issue by WK-GiHu** [keepright/keepright#61]
I see error markers 'motorways_connected_directly' as false positives.
These connections are highway=service with vehicle=no.
Please verify if vehicle=no can be accepted as OK as 
the outcome of default motorway access level + vehicle=no, equals to access=no.

In Line 136 the query use a exception if motorway connected to service=parking_aisle.
A motorway should never connect to service=parking_aisle.
Service=parking_aisle should only connect to highway=service=driveway.
Please verify if you can remove service=parking_aisle. 

Line 128 includes "'rest_area', " but no "'services', "
Please verify if "services', can be added.

Think about to remove the query "ways that come close (100 meters)", 
because this will hide bad tagged connections.

Think about to remove, `<tag k="access" v="emergency"/>,` 
the Status are Abandoned (inactive).

The DIFF talking about:
```
117,118c117,118
< //	the other way has access=no|private OR
< //	the other way is a service=parking_aisle
---
> //	the other way has access=no|private|vehicle=no OR
> //	the other way is a highway=services|rest_area
128c128
< 			t.v NOT IN (... 'unclassified', 'rest_area', 'emergency_bay')
---
> 			t.v NOT IN (... 'unclassified', 'services', 'rest_area', 'emergency_bay')
136c136
< 				(t.k='service' AND t.v='parking_aisle'))
---
> 				 (t.k='vehicle' AND t.v='no'))
```

**Comment by mueschel** [comment]
Hi,
I recently did some changes which are not yet in the repository. Could you check on the test server in an area updated on August 22nd or later?
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=9&lat=50.25735&lon=8.92623&layers=B0T&ch=0%2C270&show_ign=1&show_tmpign=1
Maybe you could also provide a link to some false positives (on this server, preferably).

**Comment by WK-GiHu** [comment]
I did not understand why "updated on or later xx" are importand?
But anyway, this link show highway=service with vehicle=no, 0270 error markers:
http://osm.mueschelsoft.de/keepright/report_map.php?zoom=12&lat=48.64328&lon=9.47125&layers=B0T&ch=0%2C270&show_ign=1&show_tmpign=1
