### ISSUE TITLE
false-positive - misspelled tags - hazard=curve

### ISSUE THREAD

**Issue by it4workflow** [keepright/keepright#65]
`This way is tagged 'hazard=curve' where "curve" looks like "curves"`, but proposed [hazard](http://wiki.openstreetmap.org/wiki/Proposed_features/hazard) mentions `curve` als value

**Comment by mueschel** [comment]
Seems like the wrong tag is used more often than the correct one in your area. I added this as an exception, now Keepright complains about 'curves':
http://osm.mueschelsoft.de/keepright/report_map.php?schema=102&error=108242588
