### ISSUE TITLE
should not warn for piste:grooming=classic;skating

### ISSUE THREAD

**Issue by Klumbumbus** [keepright/keepright#70]
e.g. http://keepright.ipax.at/report_map.php?schema=101&error=74958597

there is no reason to use `+` instead of `;` for this tag. see also https://wiki.openstreetmap.org/wiki/Piste_Maps#Grooming

**Comment by mueschel** [comment]
Correct, this case is excluded now. Check on http://osm.mueschelsoft.de/keepright/ in a few days.
