### ISSUE TITLE
RSS feed links to www.keepright.ipax.at which doesn't exist

### ISSUE THREAD

**Issue by tyrasd** [keepright/keepright#73]
Recently (around the new year), the RSS feeds were changed to link at the `www.keepright.ipax.at` subdomain (previously it pointed simply to `keepright.ipax.at`), which doesn't resolve to an IP for me. That means that all current links from the RSS feeds are broken. Manually removing the `www.` part from the Link works as a workaround, but that's very cumbersome.

**Comment by mueschel** [comment]
Looks like a configuration error of the web server. I forwarded the issue to Harald to check.

**Comment by mueschel** [comment]
Fixed. Links in RSS Feeds are correct again.
