### ISSUE TITLE
keepright.at doesn't load the map

### ISSUE THREAD

**Issue by jchamberlain** [keepright/keepright#74]
Clicking on any map, e.g., "Data Checks for Europe", logs the error:
```
Uncaught TypeError: OpenLayers.Layer.OSM.Mapnik is not a constructor
```

**Comment by mueschel** [comment]
Looks fine for me now. I guess the problem was that http://www.openlayers.org/api/OpenLayers.js could not be loaded - maybe a short server glitch?

**Comment by jchamberlain** [comment]
:p My bad. A privacy control in my browser was blocking openlayers.org. Sorry to waste your time!
