### ISSUE TITLE
Lastes dump is not up to date

### ISSUE THREAD

**Issue by oliviap-telenav** [keepright/keepright#82]
Hi, I noticed that the lastes dump ("https://keepright.at/keepright_errors.txt.bz2") is not up to date. 

Can you please tell me if the dump is updated weekly or monthly, or if will not be updated at all. 

I need it to make a weekly report about some erros in the OSM map.

I am waiting for your answer 

Thank you very much.

**Comment by mueschel** [comment]
Hi,
thanks for reporting. There was a problem with this export, but it should be running again. Keepright revisits every area only every few days, as you can see by the timestamp on the map page. Updates might not be frequent enough to generate weekly statistics.

Jan (on behalf of Harald)
