### ISSUE TITLE
changes in first column

### ISSUE THREAD

**Issue by istvanv-telenav** [keepright/keepright#84]
Hi, 
I am trying to filter out some errors based on the first column **schema**
My question is if the planet splitting map is still up to date?
I've got hundreds of rows where the schema value is above 100 and based on the map for the US the values should be between 21-60 or something along those lines
I'll paste a few rows.
Thanks in advance.

104	53226517	300	missing maxspeed	way	147281355	new	2014-01-23 10:00:00	2017-11-27 08:00:00	2016-08-25 16:40:22	gabis_telenav	478007754	-539947534	\N	\N	missing maxspeed tag					
104	93862146	192	highway-waterway	way	129753576	new	2016-12-18 00:00:00	2017-11-27 08:00:00	2016-08-25 15:22:00	gabis_telenav	472817578	-528410988	\N	\N	This $1 intersects the $2 #$3	highway	waterway	129753700		
119	40575684	130	floating islands	way	33000360	new	2013-09-24 16:00:00	2017-11-29 07:00:00	2015-09-15 15:19:34	gabis_telenav	561335870	-1332349090	\N	\N	This way is not connected to the rest of the map					
119	43553253	170	fixme-tagged items	way	295855430	new	2014-08-07 11:00:00	2017-11-29 07:00:00	2015-09-15 14:26:55	gabis_telenav	648958896	-1475944092	\N	\N	$1	&quot;highway=road&quot;				
119	79041258	130	floating islands	way	365317731	new	2015-08-21 16:00:00	2017-11-29 07:00:00	2015-09-15 14:33:53	gabis_telenav	665532759	-1452037780	\N	\N	This way is not connected to the rest of the map					
120	5316073	130	floating islands	way	31069167	new	2010-01-20 23:00:00	2017-11-29 10:00:00	2016-08-30 11:04:56	gabis_telenav	546950565	-1186967201	\N	\N	This way is not connected to the rest of the map					
120	5717112	300	missing maxspeed	way	23780631	new	2010-02-02 21:00:00	2017-11-29 10:00:00	2016-07-14 10:59:02	gabis_telenav	538907855	-1130996212	\N	\N	missing maxspeed tag

**Comment by mueschel** [comment]
There were some schemata split in ~August for keepright.at . These you can find in the SVN repository:
https://sourceforge.net/p/keepright/code/commit_browser (revisions 802/803)

**Comment by istvanv-telenav** [comment]
well this explains a lot. thank you
