### ISSUE TITLE
JOSM link not working

### ISSUE THREAD

**Issue by Mannivu** [keepright/keepright#96]
I've noticed that the JOSM link uses an https://localhost:8112/ link but to work it should use an http://localhost:8111/ link, since this is the standard JOSM configuration for remote control.

**Comment by dex2000** [comment]
As far i can see, is there no https in the code here, looks like a code-modification on keepright.at directly

**Comment by mueschel** [comment]
Correct, the code running on keepright.at is not identical to this one. I forwarded the issue to the maintainer.

**Comment by Mannivu** [comment]
Thank you. The Level0 link is different too, as I mentioned in #95.

**Comment by mueschel** [comment]
The links on keepright.at are fixed. Thank you Harald!
